---

- name: build controlc.fm and deploy to web
  hosts: local
  connection: local
  tasks:
    - name: build site using jekyll
      command: jekyll build

    # TODO: update for amazon S3 deployment
    - name: rsync _site directory
      shell: rsync --archive --progress --delete --verbose _site/ {{ rsync_host }}:{{ web_root }}

    - name: clean up _site directory in the repo
      file: name=_site state=absent
